mode: auto
openDraftPR: true
conventionalPrTitles: true
conventionalStyle: semver
branchName: '${issue.number}-${issue.title}'
gitSafeReplacementChar: '-'
branches:
  - label: bugfix
    name: main
    prefix: 'bugfix/'
    prTarget: main
conventionalLabels:
  fix:
    bug: '🐛'
    hotfix: '🚑'
